command_timeout = 100
scan_timeout = 100
follow_symlinks = false

[shell]
zsh_indicator = "ZSH"
powershell_indicator = "PSH"
disabled = false

[directory]
truncate_to_repo = false

[git_status]
use_git_executable = true

# ===== Unused modules, disabled because they showed to use > 1ms

[battery]
disabled = true

[docker_context]
disabled = true

[pulumi]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true
