#!/bin/zsh

# cheat.sh shortcut
function cheatsheet { curl http://cheat.sh/$1 }

# Unlock all GPG + SSH keys using keychain
# TODO: revamp
function unlock {
  keychain --agents "gpg" --quiet "$GPG_MAIN_KEY"
  find "$HOME/.ssh/rsa" -type f ! -name "*.pub" | while read -r i; do
    pass "ssh_$(basename $i)" | SSH_ASKPASS="$HOME/.ssh/askpass.sh" ssh-add "$i"
  done
}

# Grep processes, excluding the grep process with grep (grep!)
function pgrep {
  ps -aux | grep $1 | grep -v grep | trim # see aliases
}

# Cut space-separated columns easily
function col {
  tr -s ' ' | cut -d ' ' -f $1
}
