#!/bin/zsh

# cheat.sh shortcut
function cheatsheet { curl http://cheat.sh/$1 }

# Unlock all GPG + SSH keys using keychain
function unlock {
  eval $(keychain --eval --agents 'ssh,gpg' $(gpg -k | grep "^ " | sed -e 's/ //g'))
  find "$HOME/.ssh/rsa" -type f ! -name "*.pub" | while read -r i; do
    DISPLAY="" SSH_ASKPASS="$HOME/.ssh/askpass.sh" ssh-add "$i" <<< $(pass "ssh_$(basename $i)")
  done
}

# Grep processes, excluding the grep process with grep (grep!)
function pgrep {
  ps -aux | grep $1 | grep -v grep | trim # see aliases
}

# Cut space-separated columns easily
function col {
  tr -s ' ' | cut -d ' ' -f $1
}
