command_timeout = 1000

right_format="""$env_var"""

[env_var.OSNAME]
variable = "OSNAME"
format = "[on $env_value](white bold dimmed)"

[shell]
zsh_indicator = "ZSH"
powershell_indicator = "PSH"
disabled = false
