" General options

set nocp "Vim mode only
set bs=2 "Backspace available in insert mode
set autoread "Refresh file if modified outside of Vim

" Display, colors, font, syntax and indent

set nu "Line numbering

set t_Co=256 "Terminal colors
colorscheme vitamins

set guifont="DejaVu Sans Mono"\ 10

syntax on "Syntax highlighting

filetype plugin indent on "Indent

set showmatch

" Search options

set incsearch "Dynamic cursor while searching
set ignorecase
set smartcase

" Mapping

map j gj
map k gk

" Tab options

autocmd FileType html set tabstop=4|set shiftwidth=4|set expandtab
autocmd FileType php set tabstop=4|set shiftwidth=4|set expandtab

" Other

autocmd FileType tex setlocal spell spelllang=fr
autocmd FileType html setlocal spell spelllang=fr
autocmd FileType php setlocal spell spelllang=fr

" Abbreviations

iab itemize \begin{itemize}<CR>\item<CR>\end{itemize}<Up>
iab enumerate \begin{enumerate}<CR>\item<CR>\end{enumerate}<up>
iab bold \textbf{
iab emph \emph{
iab noindent \noindent
iab €€ \euro
