" General

execute pathogen#infect()

set nocp "Vim mode only
set bs=2 "Backspace available in insert mode
set autoread "Refresh file if modified outside of Vim

" Display, colors, font, syntax and indent

set nu "Line numbering

set t_Co=256 "Terminal colors
colorscheme vitamins

syntax on "Syntax highlighting

filetype plugin indent on "Auto indent

set showmatch

" Search options

set incsearch "Dynamic cursor while searching
set ignorecase
set smartcase

" Mapping (normal mode)

nmap j gj
nmap k gk

nmap <Space> :NERDTreeToggle<CR>

nmap tt gt
nmap TT gT
nmap tn :tabnew<CR>
nmap te :tabedit 
nmap tc :tabclose<CR>
nmap tm :tabmove 
nmap td :tabdo 

" Indent options

set shiftwidth=4
set tabstop=4

" Other

autocmd FileType tex setlocal spell spelllang=fr
autocmd FileType html setlocal spell spelllang=fr
autocmd FileType php setlocal spell spelllang=fr

set pastetoggle=<F12>

" Modules config

" LightLine
"
set laststatus=2 "Always visible

" Commands abreviations

cabbrev cil 0r ~/Documents/Licences/ISC/header.c

" Abbreviations for LaTeX

iab newp \part{
iab news \section{
iab newss \subsection{
iab newsss \subsubsection{

iab itemize \begin{itemize}<CR>\item<CR>\end{itemize}<Up>
iab enumerate \begin{enumerate}<CR>\item<CR>\end{enumerate}<up>
iab item \item

iab underline \underline{
iab bold \textbf{
iab emph \emph{

iab noindent \noindent

iab €€ \euro

iab resetsec \setcounter{section}{0}
