" --- Modules ---

" -- Vundle --

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'itchyny/lightline.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'shawncplus/phpcomplete.vim'
Plugin 'majutsushi/tagbar'
Plugin 'artur-shaik/vim-javacomplete2'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'rdnetto/YCM-Generator'
Plugin 'Valloric/YouCompleteMe'

" Plugin dependencies (Debian) :
" - Git
" - build-essential
" - cmake
" - python 2
" - ctags
" - clang

call vundle#end()

" -- Modules config --

" - LightLine -

set laststatus=2 "Always visible

" - YCM -

let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0

" --- General ---

set nocp "Vim mode only
set bs=2 "Backspace available in insert mode
filetype off "Required by Vundle

" -- Display, colors, syntax --

set nu "Line numbering

set t_Co=256 "Terminal colors
colorscheme vitamins

syntax on "Syntax highlighting

set showmatch "Show matching braces

set pastetoggle=<F12> "Toggle paste mode

" -- Indent --

filetype plugin indent on "Auto indent
set noexpandtab "Use hard tabs
set tabstop=4 "Tabs size
set shiftwidth=4

" -- Completion --

" - Java -

autocmd FileType java set omnifunc=javacomplete#Complete
imap <F4> <Plug>(JavaComplete-Imports-Add)
imap <F4> <Plug>(JavaComplete-Imports-RemoveUnused)
nmap <F4> <Plug>(JavaComplete-Imports-Add)
nmap <F4> <Plug>(JavaComplete-Imports-RemoveUnused)

" - PHP -

autocmd FileType php set omnifunc=phpcomplete#CompletePHP

" -- Search options --

set incsearch "Dynamic cursor while searching
set ignorecase
set smartcase

" -- Mapping (normal mode) --

" - Global -

nmap j gj
nmap k gk

let mapleader = ","

" - Tabs management -

nmap t<left> gT
nmap t<right> gt
nmap t<down> :tabnew<CR>
nmap tt<left> :tabmove -1<CR>
nmap tt<right> :tabmove +1<CR>
nmap t<Space> :tabnew<CR>:NERDTreeToggle<CR>

" - Modules -

nmap <Space> :NERDTreeToggle<CR>
nmap <C-t> :TagbarToggle<CR>:wincmd w<CR>

" -- Spell checking --

autocmd FileType text setlocal spell spelllang=fr
autocmd FileType tex setlocal spell spelllang=fr
autocmd FileType html setlocal spell spelllang=fr
autocmd FileType php setlocal spell spelllang=fr

" --- Commands abreviations ---

cabbrev cil 0r ~/Documents/Licences/ISC/header.c

" --- Abbreviations ---

" -- LaTeX --

autocmd FileType plaintex set filetype=tex

autocmd FileType tex iab newp \part{
autocmd FileType tex iab news \section{
autocmd FileType tex iab newss \subsection{
autocmd FileType tex iab newsss \subsubsection{
autocmd FileType tex iab § \paragraph{

autocmd FileType tex iab itemize \begin{itemize}<CR>\item<CR>\end{itemize}<Up>
autocmd FileType tex iab enumerate \begin{enumerate}<CR>\item<CR>\end{enumerate}<up>
autocmd FileType tex iab item \item

autocmd FileType tex iab underline \underline{
autocmd FileType tex iab bold \textbf{
autocmd FileType tex iab emph \emph{

autocmd FileType tex iab €€ \euro

autocmd FileType tex iab resetsec \setcounter{section}{0}

autocmd FileType tex iab pause \pause~\\

autocmd FileType tex iab -> \rightarrow
autocmd FileType tex iab <- \leftarrow
autocmd FileType tex iab $-> $\rightarrow
autocmd FileType tex iab $<- $\leftarrow

autocmd FileType tex iab --> \Rightarrow
autocmd FileType tex iab <-- \Leftarrow
autocmd FileType tex iab $--> $\Rightarrow
autocmd FileType tex iab $<-- $\Leftarrow

map <F5> :w<CR>:!pdflatex % && pdflatex %<CR><CR>
map <F6> :w<CR>:!xelatex % && xelatex %<CR><CR>
