# Modules

autoload -U compinit promptinit colors
compinit
promptinit
colors

# History file

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

setopt HIST_IGNORE_DUPS

# Prompt

setopt prompt_subst

function set_host_color {
if [ $HOST != "GW" -a $HOST != "GW-Mk2" ]
then
	echo "%{$fg[yellow]%}%B%M%b%{$reset_color%}"
else
	echo "%{$fg[cyan]%}%B%M%b%{$reset_color%}"
fi
}

function set_user_color {
if [ $USER = "root" ]
then
	echo "%{$fg[red]%}%B%n%b%{$reset_color%}"
else
	echo "%{$fg[green]%}%B%n%b%{$reset_color%}"
fi
}

function get_git_branch {
branch=`git symbolic-ref HEAD 2> /dev/null`
if [ $branch ]
then
	echo "%{$fg[blue]%}(${branch#refs/heads/})%{$reset_color%}"
fi
}

function set_return_code_color {
if [ $? != 0 ]
then
	echo "%{$fg[red]%}%B%?%b%{$reset_color%}"
else
	echo "%B%?%b"
fi
}

host='`set_host_color`'
user='`set_user_color`'
git_branch='`get_git_branch`'
return_code='`set_return_code_color`'

PROMPT="┌[$host]-[$user:%~]$git_branch
└─────╸ "
RPROMPT="$return_code ╺┘"

# Colors

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Environment variables

export EDITOR="vim"
export PATH=$PATH:/sbin/:/usr/sbin/:/home/quentin/.bin/:/home/quentin/Autre/Scripts/:/opt/lampp/bin/

eval `keychain --eval --agents ssh -Q --quiet`

# Aliases

## Existing commands

alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias rm="rm -I"
alias su="su -"
alias mu="sh -c su"

## Global

alias mountmtp="mkdir /media/quentin/mtp/ && jmtpfs /media/quentin/mtp/"
alias umountmtp="fusermount -u /media/quentin/mtp/ && rmdir /media/quentin/mtp/"
alias mountseedbox="sshfs seedbox: /media/quentin/seedbox/ -o follow_symlinks,transform_symlinks"
alias umountseedbox="fusermount -u /media/quentin/seedbox/"

## Git

alias gs="git status"
alias ga="git add"
alias gr="git rm"
alias gm="git mv"
alias gd="git diff"
alias gl="git log"
alias gc="git commit -m"
alias gC="git checkout"
alias gf="git fetch"
alias gM="git merge"
alias gp="git push"
alias gP="git pull"
alias gS="git stash"
alias gb="git branch -vv"

## SSH

alias ssh="keychain --agents ssh --quiet id_rsa --timeout 60; ssh"
alias scp="keychain --agents ssh --quiet id_rsa --timeout 60; scp"
alias trssh="ssh quentin@liquidus88.ddns.net"
alias trtunnel="ssh -vTND 2222 quentin@liquidus88.ddns.net"
alias sshavec="ssh -o PasswordAuthentication=yes quentin@10.0.0.10"

alias mounttr="sshfs quentin@192.168.1.28:/home/quentin/ /media/quentin/tr/home/ & sshfs quentin@192.168.1.28:/var/lib/transmission-daemon/downloads/ /media/quentin/tr/transmission/ & sshfs quentin@192.168.1.28:/var/www/ /media/quentin/tr/www/"
alias umounttr="fusermount -u /media/quentin/tr/home/ & fusermount -u /media/quentin/tr/transmission/ & fusermount -u /media/quentin/tr/www/"
alias mounttj="sshfs quentin@192.168.1.27:/home/quentin/ /media/quentin/tj/"
alias umounttj="fusermount -u /media/quentin/tj/"

alias mounttronline="sshfs quentin@liquidus88.ddns.net:/home/quentin/ /media/quentin/tr/home/ & sshfs quentin@liquidus88.ddns.net:/var/lib/transmission-daemon/downloads/ /media/quentin/tr/transmission/ & sshfs quentin@liquidus88.ddns.net:/var/www/ /media/quentin/tr/www/"
alias umounttronline="fusermount -u /media/quentin/tr/home/ & fusermount -u /media/quentin/tr/transmission/ & fusermount -u /media/quentin/tr/www/"

## Other

alias winreboot="net rpc shutdown -r -I 192.168.1.26 -U quentin"
alias resound="killall mpd && killall pulseaudio && pulseaudio --start && mpd"
alias convsubs="vim -p *.srt '+tabdo set ff=unix' '+tabdo set fileencoding=utf8' '+wqall'"

## Temporary aliases

alias mana="$HOME/.i3/workspaces/mana; exit"

# Functions

function autoindent {
vim -s ~/Documents/Vrac/indent.scr $1
}

function mkcd {
mkdir $1
cd $1
}

function man {
env LESS_TERMCAP_md=$'\033[1;34m' \
	LESS_TERMCAP_us=$'\033[0;36m' \
	LESS_TERMCAP_so=$'\033[1;31m' \
	LESS_TERMCAP_mb=$'\033[0m' \
	LESS_TERMCAP_me=$'\033[0m' \
	LESS_TERMCAP_se=$'\033[0m' \
	LESS_TERMCAP_ue=$'\033[0m' \
	man "$@"
}

# User and machine specific conf

if [ $USER = "quentin" ]
then
	if [ $HOST = "GW" -o $HOST = "GW-Mk2" ]
	then
		fortune fr -s -o | cowsay -f /usr/share/cowsay/cows/unipony-smaller.cow
		tasky
	fi
	if [ -d $HOME/.rvm ]
	then
		export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
		source $HOME/.rvm/scripts/rvm
	fi
fi

if [ $USER = "root" ]
then
	function ufwls { j=1; ufw status | grep "^[0-9]" | while read i; do echo $j".\t"$i; j=$((j+1)); done }
fi
