#!/bin/sh

# shellcheck disable=SC1094
# shellcheck disable=SC3020

# Modules
autoload -U compinit promptinit colors
compinit
promptinit
colors

# History file
export HISTSIZE=1000
export SAVEHIST=1000
export HISTFILE="$HOME/.histfile"
setopt HIST_IGNORE_DUPS

# Key bindings
zle -N fzf-file-widget
bindkey '^P' fzf-file-widget

# Plugins
. /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Aliases and functions
[ -f "$HOME/.aliases.sh" ] && . "$HOME/.aliases.sh"
[ -f "$HOME/.functions.sh" ] && . "$HOME/.functions.sh"

# Tools
eval "$(starship init zsh)" # Starship
eval "$(direnv hook zsh)" # Direnv
. /usr/share/fzf/key-bindings.zsh # FZF

# SSH Agent
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    #ssh-agent > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [ ! -f "$SSH_AUTH_SOCK" ]; then
    #source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi

# Machine/setup specific config
[ -f "$HOME/.zshrc.wsl" ] && . "$HOME/.zshrc.wsl"
[ -f "$HOME/.zshrc.local" ] && . "$HOME/.zshrc.local"

# Check Dotfiles changes in the background
if [ "$(id -u)" -ne "0" ]; then
  (&>/dev/null dotfiles -c &)
  dotfiles -w
fi
