#!/bin/sh

# shellcheck disable=SC1094
# shellcheck disable=SC3020

# Modules
autoload -U compinit promptinit colors
compinit
promptinit
colors

# History file
export HISTSIZE=1000
export SAVEHIST=1000
export HISTFILE="$HOME/.histfile"
setopt HIST_IGNORE_DUPS

# Key bindings
zle -N fzf-file-widget
bindkey '^P' fzf-file-widget

# Plugins
ZSH_SYN_HIG_DEB=/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_SYN_HIG_ARCH=usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[ -f "$ZSH_SYN_HIG_DEB" ] && . "$ZSH_SYN_HIG_DEB"
[ -f "$ZSH_SYN_HIG_ARCH" ] && . "$ZSH_SYN_HIG_ARCH"

# Aliases and functions
[ -f "$HOME/.aliases.sh" ] && . "$HOME/.aliases.sh"
[ -f "$HOME/.functions.sh" ] && . "$HOME/.functions.sh"

# Tools
eval "$(starship init zsh)" # Starship
eval "$(direnv hook zsh)" # Direnv
#eval "$(keychain --eval --agents "ssh" --quiet)" # Keychain (disable for now)

# FZF
FZF_DEB_PATH=/usr/share/doc/fzf/examples/key-bindings.zsh
FZF_ARCH_PATH=/usr/share/fzf/key-bindings.zsh
[ -f "$FZF_DEB_PATH" ] && . "$FZF_DEB_PATH"
[ -f "$FZF_ARCH_PATH" ] && . "$FZF_ARCH_PATH"

# Machine/setup specific config
[ -f "$HOME/.zshrc.wsl" ] && . "$HOME/.zshrc.wsl"
[ -f "$HOME/.zshrc.local" ] && . "$HOME/.zshrc.local"

# Check Dotfiles changes in the background
if [ "$(id -u)" -ne "0" ]; then
  (&>/dev/null dotfiles -c &)
  dotfiles -w
fi
